# Generated by Django 3.0.8 on 2021-08-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_date', models.DateField(unique=True)),
                ('menu_greeting_msg', models.CharField(blank=True, default="Here is today's menu", max_length=255)),
                ('menu_goodbye_msg', models.CharField(blank=True, default='Have a nice day!', max_length=255)),
            ],
        ),
    ]
