# Generated by Django 3.0.8 on 2021-08-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_option_1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_option_2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_option_3',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_option_4',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
