# Generated by Django 3.0.8 on 2021-09-05 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20210827_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_option_chosen', models.CharField(max_length=255)),
                ('menu_option_chosen_comment', models.CharField(blank=True, default='', max_length=255)),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menus.Menu')),
            ],
        ),
    ]
