# Generated by Django 3.0.8 on 2021-09-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0004_auto_20210905_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='menurequest',
            name='menu_request_employee_name',
            field=models.CharField(default='empleado', max_length=255),
            preserve_default=False,
        ),
    ]
